/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get reservation by ID
         * @description Retrieves a specific reservation by its unique identifier
         */
        get: operations["getById"];
        /**
         * Update an existing reservation
         * @description Updates a reservation. Only PENDING reservations can be modified.
         */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_1"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a car by ID */
        get: operations["getById_2"];
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_3"];
        put: operations["update_3"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Register a new customer account
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh JWT token
         * @description Generate a new JWT token for authenticated user
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate user and return JWT token
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reservations with optional filters, pagination and sorting
         * @description Retrieve reservations with comprehensive filtering and search capabilities.
         *
         *     **Search Functionality:**
         *     The search parameter enables unified searching across multiple fields in a single API call:
         *     - Customer information: first name, last name, full name, email address, phone number
         *     - Reservation details: reservation ID (exact match prioritized)
         *     - Car information: display name, model
         *     - Branch information: branch name
         *
         *     **Search Behavior:**
         *     - Case-insensitive partial matching across all searchable fields
         *     - Minimum 2 characters required for search terms
         *     - Maximum 100 characters allowed
         *     - Exact reservation ID matches are prioritized in results
         *     - Results ordered by relevance (exact ID matches first, then by creation date)
         *
         *     **Performance:**
         *     - Single optimized database query with JOINs
         *     - Database indexes ensure sub-500ms response times
         *     - Supports concurrent search operations
         *
         *     **Backward Compatibility:**
         *     - All existing filter parameters remain functional
         *     - When search parameter is provided, it takes precedence over customer-based filtering
         *     - Pagination and sorting work seamlessly with search results
         *
         */
        get: operations["listWithFilters"];
        put?: never;
        /**
         * Create a new reservation
         * @description Creates a new car reservation with automatic price calculation and availability validation
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a reservation
         * @description Confirms a PENDING reservation, changing its status to CONFIRMED
         */
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a reservation */
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a reservation
         * @description Cancels a reservation, changing its status to CANCELLED
         */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule a maintenance */
        post: operations["schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers with pagination and sorting */
        get: operations["list"];
        put?: never;
        /** Create a customer */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cars with pagination, sorting, and filtering
         * @description Returns a paginated, sorted, and filtered list of cars. Filter by any combination of fields (vin, make, model, year, category, transmission, fuelType, minSeats, maxPrice). Sorting and pagination are supported via standard Spring Data parameters.
         */
        get: operations["list_1"];
        put?: never;
        /** Create a car */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches with pagination and sorting */
        get: operations["list_2"];
        put?: never;
        /** Create a branch */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Get current authenticated user information
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List maintenance records with optional filters, pagination and sorting */
        get: operations["listWithFilters_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["scheduledForDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/searchany": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search customers by a single value in email, firstName, lastName, or city (OR logic)
         * @description Returns a paginated list of customers where the search value matches any of the following fields: email, firstName, lastName, or city. The search is case-insensitive and uses OR logic.
         */
        get: operations["searchAny"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search customers with optional filters, pagination and sorting */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/deleted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deleted cars with pagination and sorting */
        get: operations["listDeleted"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/branch/{branchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cars by branch with pagination and sorting */
        get: operations["listByBranch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find available cars by date range with optional filters */
        get: operations["findAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search branches by name with pagination and sorting */
        get: operations["searchByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches/by-name-and-city": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find branches by name and city
         * @description Returns a list of branches filtered by both name and city, with optional pagination.
         */
        get: operations["byNameAndCity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches/by-country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byCountry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches/by-city": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byCity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReservationRequestDto: {
            /** Format: int64 */
            customerId: number;
            /** Format: int64 */
            carId: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: int64 */
            pickupBranchId: number;
            /** Format: int64 */
            dropoffBranchId: number;
            notes?: string;
            endDateAfterStartDate?: boolean;
        };
        BranchResponseDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            address?: string;
            city?: string;
            country?: string;
            phone?: string;
            email?: string;
            openingHours?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CarListResponseDto: {
            /** Format: int64 */
            id?: number;
            vin?: string;
            make?: string;
            model?: string;
            /** Format: int32 */
            year?: number;
            /** @enum {string} */
            category?: "ECONOMY" | "COMPACT" | "INTERMEDIATE" | "STANDARD" | "FULL_SIZE" | "PREMIUM" | "LUXURY" | "SUV" | "VAN";
            /** @enum {string} */
            transmission?: "MANUAL" | "AUTOMATIC" | "CVT";
            /** @enum {string} */
            fuelType?: "GASOLINE" | "DIESEL" | "HYBRID" | "ELECTRIC";
            /** Format: int32 */
            seats?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "RENTED" | "MAINTENANCE" | "OUT_OF_SERVICE";
            dailyPrice?: number;
            color?: string;
            displayName?: string;
            branchName?: string;
        };
        CustomerResponseDto: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            driverLicenseNo?: string;
            /** Format: date */
            dateOfBirth?: string;
            address?: string;
            city?: string;
            country?: string;
            /** Format: date */
            licenseExpiryDate?: string;
            fullName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ReservationResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
            totalPrice?: number;
            currency?: string;
            notes?: string;
            customer?: components["schemas"]["CustomerResponseDto"];
            car?: components["schemas"]["CarListResponseDto"];
            pickupBranch?: components["schemas"]["BranchResponseDto"];
            dropoffBranch?: components["schemas"]["BranchResponseDto"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            durationDays?: number;
            dailyRate?: number;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: Record<string, never>;
            };
        };
        CustomerRequestDto: {
            firstName: string;
            lastName: string;
            email: string;
            phone?: string;
            driverLicenseNo: string;
            /** Format: date */
            dateOfBirth: string;
            address: string;
            city: string;
            country: string;
            /** Format: date */
            licenseExpiryDate: string;
        };
        CarRequestDto: {
            vin: string;
            make: string;
            model: string;
            /** Format: int32 */
            year: number;
            /** @enum {string} */
            category: "ECONOMY" | "COMPACT" | "INTERMEDIATE" | "STANDARD" | "FULL_SIZE" | "PREMIUM" | "LUXURY" | "SUV" | "VAN";
            /** @enum {string} */
            transmission: "MANUAL" | "AUTOMATIC" | "CVT";
            /** @enum {string} */
            fuelType: "GASOLINE" | "DIESEL" | "HYBRID" | "ELECTRIC";
            /** Format: int32 */
            seats: number;
            /** Format: int32 */
            mileage?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "RENTED" | "MAINTENANCE" | "OUT_OF_SERVICE";
            dailyPrice: number;
            /** Format: int64 */
            branchId: number;
            color?: string;
            licensePlate?: string;
            insurancePolicy?: string;
        };
        CarResponseDto: {
            /** Format: int64 */
            id?: number;
            vin?: string;
            make?: string;
            model?: string;
            /** Format: int32 */
            year?: number;
            /** @enum {string} */
            category?: "ECONOMY" | "COMPACT" | "INTERMEDIATE" | "STANDARD" | "FULL_SIZE" | "PREMIUM" | "LUXURY" | "SUV" | "VAN";
            /** @enum {string} */
            transmission?: "MANUAL" | "AUTOMATIC" | "CVT";
            /** @enum {string} */
            fuelType?: "GASOLINE" | "DIESEL" | "HYBRID" | "ELECTRIC";
            /** Format: int32 */
            seats?: number;
            /** Format: int32 */
            mileage?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "RENTED" | "MAINTENANCE" | "OUT_OF_SERVICE";
            dailyPrice?: number;
            color?: string;
            licensePlate?: string;
            insurancePolicy?: string;
            /** Format: date */
            lastServiceDate?: string;
            /** Format: date */
            nextServiceDate?: string;
            displayName?: string;
            branch?: components["schemas"]["BranchResponseDto"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BranchRequestDto: {
            name: string;
            address: string;
            city: string;
            country: string;
            phone?: string;
            email?: string;
            openingHours?: string;
            active?: boolean;
        };
        RegisterRequestDto: {
            username: string;
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            phone?: string;
        };
        UserResponseDto: {
            /** Format: int64 */
            id?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            phone?: string;
            enabled?: boolean;
            roles?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LoginResponseDto: {
            user?: components["schemas"]["UserResponseDto"];
            access_token?: string;
            token_type?: string;
            /** Format: int64 */
            expires_in?: number;
            /** Format: date-time */
            expires_at?: string;
        };
        LoginRequestDto: {
            email: string;
            password: string;
        };
        Branch: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            address?: string;
            city?: string;
            country?: string;
            phone?: string;
            email?: string;
            openingHours?: string;
            cars?: components["schemas"]["Car"][];
            employees?: components["schemas"]["Employee"][];
            pickupReservations?: components["schemas"]["Reservation"][];
            dropoffReservations?: components["schemas"]["Reservation"][];
        };
        Car: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            vin?: string;
            make?: string;
            model?: string;
            /** Format: int32 */
            year?: number;
            /** @enum {string} */
            category?: "ECONOMY" | "COMPACT" | "INTERMEDIATE" | "STANDARD" | "FULL_SIZE" | "PREMIUM" | "LUXURY" | "SUV" | "VAN";
            /** @enum {string} */
            transmission?: "MANUAL" | "AUTOMATIC" | "CVT";
            /** @enum {string} */
            fuelType?: "GASOLINE" | "DIESEL" | "HYBRID" | "ELECTRIC";
            /** Format: int32 */
            seats?: number;
            /** Format: int32 */
            mileage?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "RENTED" | "MAINTENANCE" | "OUT_OF_SERVICE";
            dailyPrice?: number;
            branch?: components["schemas"]["Branch"];
            color?: string;
            licensePlate?: string;
            insurancePolicy?: string;
            /** Format: date */
            lastServiceDate?: string;
            /** Format: date */
            nextServiceDate?: string;
            deleted?: boolean;
            reservations?: components["schemas"]["Reservation"][];
            maintenanceRecords?: components["schemas"]["Maintenance"][];
            displayName?: string;
            available?: boolean;
        };
        Customer: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            driverLicenseNo?: string;
            /** Format: date */
            dateOfBirth?: string;
            address?: string;
            city?: string;
            country?: string;
            /** Format: date */
            licenseExpiryDate?: string;
            reservations?: components["schemas"]["Reservation"][];
            fullName?: string;
            /** Format: int32 */
            age?: number;
            licenseValid?: boolean;
        };
        Employee: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            user?: components["schemas"]["User"];
            employeeId?: string;
            branch?: components["schemas"]["Branch"];
            position?: string;
            /** Format: date */
            hireDate?: string;
            salary?: number;
            isActive?: boolean;
            maintenanceRecords?: components["schemas"]["Maintenance"][];
        };
        Maintenance: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            car?: components["schemas"]["Car"];
            employee?: components["schemas"]["Employee"];
            /** @enum {string} */
            maintenanceType?: "ROUTINE" | "REPAIR" | "INSPECTION" | "EMERGENCY" | "RECALL";
            description?: string;
            /** Format: date */
            scheduledDate?: string;
            /** Format: date */
            completedDate?: string;
            cost?: number;
            currency?: string;
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
            notes?: string;
        };
        Payment: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            reservation?: components["schemas"]["Reservation"];
            amount?: number;
            currency?: string;
            /** @enum {string} */
            status?: "PENDING" | "AUTHORIZED" | "CAPTURED" | "FAILED" | "REFUNDED";
            /** @enum {string} */
            paymentMethod?: "CREDIT_CARD" | "DEBIT_CARD" | "CASH" | "BANK_TRANSFER" | "DIGITAL_WALLET";
            provider?: string;
            transactionRef?: string;
            /** Format: date-time */
            paymentDate?: string;
            notes?: string;
            paid?: boolean;
        };
        Reservation: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            customer?: components["schemas"]["Customer"];
            car?: components["schemas"]["Car"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            pickupBranch?: components["schemas"]["Branch"];
            dropoffBranch?: components["schemas"]["Branch"];
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
            totalPrice?: number;
            currency?: string;
            notes?: string;
            payments?: components["schemas"]["Payment"][];
            active?: boolean;
            /** Format: int64 */
            durationInDays?: number;
        };
        Role: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            description?: string;
            users?: components["schemas"]["User"][];
        };
        User: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            username?: string;
            email?: string;
            password?: string;
            firstName?: string;
            lastName?: string;
            phone?: string;
            enabled?: boolean;
            roles?: components["schemas"]["Role"][];
            employee?: components["schemas"]["Employee"];
            fullName?: string;
        };
        MaintenanceScheduleRequestDto: {
            /** Format: int64 */
            carId: number;
            /** @enum {string} */
            type: "ROUTINE" | "REPAIR" | "INSPECTION" | "EMERGENCY" | "RECALL";
            description: string;
            /** Format: date */
            scheduledDate: string;
        };
        Page: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: Record<string, never>[];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        PageMaintenance: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["Maintenance"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageCustomerResponseDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["CustomerResponseDto"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageCarListResponseDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["CarListResponseDto"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageBranchResponseDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["BranchResponseDto"][];
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            numberOfElements?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Reservation ID
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponseDto"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Reservation ID
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationRequestDto"];
            };
        };
        responses: {
            /** @description Reservation updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponseDto"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Reservation cannot be updated (not PENDING) or car not available */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarResponseDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarResponseDto"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponseDto"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponseDto"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Invalid registration data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Username or email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description User not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Invalid login credentials */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    listWithFilters: {
        parameters: {
            query?: {
                /**
                 * @description Filter by specific customer ID
                 * @example 123
                 */
                customerId?: number;
                /**
                 * @description Filter by specific car ID
                 * @example 456
                 */
                carId?: number;
                /**
                 * @description Filter by reservation status
                 * @example CONFIRMED
                 */
                status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
                /**
                 * @description Filter by pickup/dropoff branch ID
                 * @example 789
                 */
                branchId?: number;
                /**
                 * @description Filter reservations starting from this date (inclusive)
                 * @example 2024-01-01
                 */
                startDate?: string;
                /**
                 * @description Filter reservations ending before this date (inclusive)
                 * @example 2024-12-31
                 */
                endDate?: string;
                /** @description Search term to find reservations across multiple fields. Searches:
                 *     - Customer: first name, last name, email, phone number
                 *     - Reservation: ID (exact matches prioritized)
                 *     - Car: display name, model
                 *     - Branch: name
                 *
                 *     Requirements:
                 *     - Minimum 2 characters
                 *     - Maximum 100 characters
                 *     - Case-insensitive partial matching
                 *     - Alphanumeric characters, spaces, hyphens, dots, @ symbols allowed
                 *      */
                search?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved reservations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationRequestDto"];
            };
        };
        responses: {
            /** @description Reservation created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponseDto"];
                };
            };
            /** @description Invalid request data or validation errors */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Car not available for selected dates */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Reservation ID
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation confirmed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponseDto"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Reservation cannot be confirmed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponseDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Reservation ID
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation cancelled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponseDto"];
                };
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Reservation cannot be cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Maintenance"];
                };
            };
        };
    };
    complete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Maintenance"];
                };
            };
        };
    };
    cancel_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Maintenance"];
                };
            };
        };
    };
    schedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceScheduleRequestDto"];
            };
        };
        responses: {
            /** @description Scheduled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Maintenance"];
                };
            };
            /** @description Validation/Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCustomerResponseDto"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerResponseDto"];
                };
            };
            /** @description Validation/Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                vin?: string;
                make?: string;
                model?: string;
                year?: number;
                category?: "ECONOMY" | "COMPACT" | "INTERMEDIATE" | "STANDARD" | "FULL_SIZE" | "PREMIUM" | "LUXURY" | "SUV" | "VAN";
                transmission?: "MANUAL" | "AUTOMATIC" | "CVT";
                fuelType?: "GASOLINE" | "DIESEL" | "HYBRID" | "ELECTRIC";
                minSeats?: number;
                maxPrice?: number;
                availableFrom?: string;
                availableTo?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarListResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarResponseDto"];
                };
            };
            /** @description Validation/Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarResponseDto"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageBranchResponseDto"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponseDto"];
                };
            };
            /** @description Validation/Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description User not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    listWithFilters_1: {
        parameters: {
            query?: {
                carId?: number;
                employeeId?: number;
                status?: "SCHEDULED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
                maintenanceType?: "ROUTINE" | "REPAIR" | "INSPECTION" | "EMERGENCY" | "RECALL";
                branchId?: number;
                startDate?: string;
                endDate?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageMaintenance"];
                };
            };
        };
    };
    scheduledForDate: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Maintenance"][];
                };
            };
        };
    };
    searchAny: {
        parameters: {
            query: {
                /**
                 * @description Search value to match against email, firstName, lastName, or city
                 * @example smith
                 */
                search: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful search */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerResponseDto"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                email?: string;
                firstName?: string;
                lastName?: string;
                city?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCustomerResponseDto"];
                };
            };
        };
    };
    listDeleted: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCarListResponseDto"];
                };
            };
        };
    };
    listByBranch: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path: {
                branchId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCarListResponseDto"];
                };
            };
        };
    };
    findAvailable: {
        parameters: {
            query: {
                branchId: number;
                startDate: string;
                endDate: string;
                category?: "ECONOMY" | "COMPACT" | "INTERMEDIATE" | "STANDARD" | "FULL_SIZE" | "PREMIUM" | "LUXURY" | "SUV" | "VAN";
                transmission?: "MANUAL" | "AUTOMATIC" | "CVT";
                fuelType?: "GASOLINE" | "DIESEL" | "HYBRID" | "ELECTRIC";
                minSeats?: number;
                maxPrice?: number;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCarListResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    searchByName: {
        parameters: {
            query: {
                name: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageBranchResponseDto"];
                };
            };
        };
    };
    byNameAndCity: {
        parameters: {
            query: {
                name: string;
                city: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponseDto"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    byCountry: {
        parameters: {
            query: {
                country: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponseDto"][];
                };
            };
        };
    };
    byCity: {
        parameters: {
            query: {
                city: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BranchResponseDto"][];
                };
            };
        };
    };
}
